export const store = {
  test: '',
  ProjectName: '',
  ProjectId: '',
  TaskName: '',
  TaskId: '',
  MeetingName: '',
  MeetingId: '',
  projectArray: [{
    'ProjectName': 'Default',
    'date':'-',
    'id': 'aaaaa',
    'status': 'join',
  }],
  taskArray: [],
  meetingArray: [],
  projectState: {
    name: '',
    details: '',
  },
  meetingState: {
    name: '',
    details: '',
    startDate: '',
    startHour: '',
    startMinutes: '',
    endHour: '',
    endMinutes: '',
    endDate: '',
    location: '',
  },
  taskState: {
    name: '',
    details: '',
  },
  newFeedArray: [],
  checklistTaskArray: [],
}